filebeat.inputs:
- type: log
  paths:
    - '/services/data/*.log'

- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

output.logstash:
  hosts: ["127.0.0.1:5044"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
