---
  - name: "Install required apt packages"
    apt:
      package:
        - openvpn
        - easy-rsa

  - name: "Add setup-team-openvpn.sh script"
    copy:
      src: setup-team-openvpn.sh
      dest: /opt/setup-team-openvpn.sh
      mode: "755"

  - name: "Add systemd setup-team-openvpn.service"
    copy:
      src: setup-team-openvpn.service
      dest: /etc/systemd/system/setup-team-openvpn.service

  - name: "Enable systemd setup-team-openvpn.service"
    service:
      name: setup-team-openvpn
      enabled: yes

  - name: "Enable ipv4 forward"
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes

  - name: allow related/established forward traffic
    iptables:
      chain: FORWARD
      ctstate: [RELATED, ESTABLISHED]
      jump: ACCEPT

  - name: "Allow traffic from team to game"
    iptables:
      chain: FORWARD
      in_interface: team
      out_interface: game
      jump: ACCEPT

  - name: masquerade outgoing traffic on the game interface
    iptables:
      table: nat
      chain: POSTROUTING
      out_interface: game
      jump: MASQUERADE

  - name: allow OpenVPN input traffic
    iptables:
      chain: INPUT
      in_interface: eth0
      destination_port: "1194"
      protocol: udp
      jump: ACCEPT

  - name: persist iptables config
    shell: "iptables-save > /etc/iptables/rules.v4"
