---
  - name: Disable and stop services
    service:
      name: dc@{ item.key }}
      state: stopped
      enabled: no
    with_dict:
      - "{{ dockered_services }}"

  - name: Clean local services cache
    become: no
    local_action:
      module: file
      path: ./services/{{inventory_hostname}}/{{ item.key }}
      state: absent
    with_dict:
      - "{{ dockered_services }}"

  - name: Clone dockered services locally
    become: no
    local_action:
      module: git
      repo: "{{ item.value }}"
      dest: ./services/{{inventory_hostname}}/{{ item.key }}
      accept_hostkey: yes
    with_dict:
      - "{{ dockered_services }}"

  - name: Copy dockered services to /services
    copy:
      src: ./services/{{inventory_hostname}}/{{ item.key }}/
      dest: /services/{{ item.key }}
    with_dict:
      - "{{ dockered_services }}"

  - name: Enable and start dockered services
    service:
      name: dc@{{ item.key }}
      state: restarted
      enabled: yes
    with_dict:
      - "{{ dockered_services }}"